project:
  type: website
  output-dir: docs

website:
  title: "NikhilsWebsite"
  navbar:
    left:
    - about.qmd
    - Dummy1.qmd
    - Dummy2.qmd
    - Dummy3.qmd
    - Dummy4.qmd
    - Dummy5.qmd
    - Dummy6.qmd
    
    

format:
  html:
    theme: sandstone